### ISSUE TITLE
HArd to find th web link of the web page https://ekaroune.github.io/The-Open-Archaeobotanist/

### ISSUE THREAD

**Issue by yvanlebras** [EKaroune/The-Open-Archaeobotanist#1]
Amazing job Emma !!

Maybe you can ameliorate your repo providing direct link of the resulting website, so https://ekaroune.github.io/The-Open-Archaeobotanist/ , on the README.md file and maybe also on the github description. What do you think about that ?

**Comment by EKaroune** [comment]
Added link in the description
